# Generated by Django 4.2.1 on 2023-05-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
